//function start() {
	//cm.resetBossLog("扎昆");
	//cm.sendOk("已挑战扎昆次数"+cm.getBossLog("扎昆")+"次");
	//cm.dispose();
//}
function start() {
	    cm.resetBossLog("蝙蝠魔");
		cm.resetBossLog("班·雷昂");
	    cm.resetBossLog("扎昆");
		cm.resetBossLog("进阶扎昆");
		cm.resetBossLog("品克缤");
		cm.resetBossLog("混沌品克缤");
		cm.resetBossLog("钻机");
		cm.resetBossLog("强化的钻机");
		cm.resetBossLog("阿卡伊勒");
		cm.resetBossLog("希纳斯");
		cm.resetBossLog("普通皮埃尔");
		cm.resetBossLog("普通血腥女皇");
		cm.resetBossLog("普通贝伦");
		cm.resetBossLog("普通半半");
		cm.resetBossLog("古树钥匙");
		cm.resetBossLog("进阶皮埃尔");
		cm.resetBossLog("进阶血腥女皇");
		cm.resetBossLog("进阶贝伦");
		cm.resetBossLog("进阶半半");
		cm.resetBossLog("贝勒德");
		cm.resetEventCount("贝勒德");
		cm.resetBossLog("麦格纳斯");
		cm.resetBossLog("乌鲁斯");
		cm.sendOk("#r重置成功.祝你游戏愉快!");
	    cm.dispose();
}
