using System;

namespace FMOD
{
	public enum CAPS
	{
		NONE,
		HARDWARE,
		HARDWARE_EMULATED,
		OUTPUT_MULTICHANNEL = 4,
		OUTPUT_FORMAT_PCM8 = 8,
		OUTPUT_FORMAT_PCM16 = 16,
		OUTPUT_FORMAT_PCM24 = 32,
		OUTPUT_FORMAT_PCM32 = 64,
		OUTPUT_FORMAT_PCMFLOAT = 128,
		REVERB_LIMITED = 8192
	}
}
